### PR TITLE
Remove unused external JS links and update prefixes

### PR DESCRIPTION
**Pull request by csarven**
Minor update. No change to functionality.

### CODE REVIEW

**Review by megoth — APPROVED** [review]
LGTM

**Comment by melvincarvalho** [comment]
Im sure you're aware, but just in case.  

Changes to this library need to be propagated upstream to dependencies (mashlib and node-solid-server) via npm as well.

**Comment by RubenVerborgh** [comment]
> Changes to this library need to be propagated upstream to dependencies (mashlib and node-solid-server) via npm as well.

That's not correct and it's important we get this right.

As long as the dependency is within the semver range of those dependents, then that version will be used automatically on installs.

You _might_ want to change the package-lock.json of dependents (and you can decide individually which ones) such that, as a _developer_ checking out the repository, you use those latest versions. But again, non-developers doing a package installation from npm will get the latest dependencies.

**Comment by csarven** [comment]
So, is there something you'd like me to do further for this PR? AFAICT, the current changes in this PR doesn't require an update to package*.json. If package*.json is currently behind, that's another matter.

**Comment by RubenVerborgh** [comment]
The PR is fine.

**Comment by melvincarvalho** [comment]
> That's not correct and it's important we get this right.

@RubenVerborgh Agree.  Perhaps we could add some notes somewhere, eg in an .md file.  

I think we're saying the same thing.  

In either case, the version of npm will be need to be bumped for this package.

That will then propagate to dependencies (libraries, and ultimately, pods) either semi-automatically (with a minor version) or manually (for a patch version) depending which is deemed appropriate.  

In this case there are fewer round trips, and better privacy, but functionality should remain backwards compatible, so could be either.

**Pull request merged**
