### PR TITLE
Add Webpack config

### PR DESCRIPTION
**Pull request by Vinnl**
There were references to Webpack and Babel in the code, but it appears that the code was published as-is anyway.

I've now added Webpack configuration and set up Babel. I tried to replicate the workings of the current code with the built code, and it appears to run fine locally. However, I don't know how the code is usually published, and I don't have that much experience with the data browser yet that I can really stress test all edge cases. In other words: please do feel free to extensively point out how this could be better :)

This could pave the way to fixing #69.

### CODE REVIEW

**Comment by Vinnl** [comment]
Oops, forgot to actually activate Babel... One moment >.<

**Comment by Vinnl** [comment]
Sorry about that, fixed now.

**Review by megoth — APPROVED** [review]
LGTM

**Comment by megoth** [comment]
Merging this into branch revamp until we have things a bit more in order.

**Pull request merged**
