### PR TITLE
remove temporary workarround for npm 7

### PR DESCRIPTION
**Pull request by angelo-v**
Should work without the workarround now

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
> Should work without the workarround now

Why? Has npm been updated?

**Comment by angelo-v** [comment]
No, I updated the package lock

**Comment by RubenVerborgh** [comment]
That means all devs have to be on npm 7 though. Is that a good idea?

**Comment by angelo-v** [comment]
Are you sure that is a prerequisite?

**Comment by RubenVerborgh** [comment]
Older npms will just overwrite the lockfile and break things again.

**Comment by angelo-v** [comment]
I just tested it with npm 6: test, lint, build and ci run trough fine

**Comment by angelo-v** [comment]
> Older npms will just overwrite the lockfile and break things again.

That's a general issue with mixing npm versions isn't it?

**Comment by RubenVerborgh** [comment]
> That's a general issue with mixing npm versions isn't it?

Yep, hence the current setup.

**Comment by angelo-v** [comment]
So your concern is, if someone with npm 6 overrides the current lock file the build would break again, if we merge this?

**Comment by RubenVerborgh** [comment]
Yes; given that we are not mandating npm 7 for this project, I assume everyone is running npm 6.

**Comment by angelo-v** [comment]
Ok, I tested this as well:

1. `npm install` using npm 6 --> this changes the lockfiles
2. delete node_modules & then with npm 7:
  - `npm ci`
  - `npm test`
  - `npm run build`

It runs without error, the former problems do not occur

**Comment by angelo-v** [comment]
If you wish I can add a lockfile generated from npm 6 into this PR

**Comment by timea-solid** [comment]
This was already updated.

**Pull request closed without merging**
