### PR TITLE
Remove webpack build from main build task

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by michielbdejong** [comment]
I think since we're doing a webpack build in mashlib, the one in solid-panes is not really necessary?

**Review by megoth — APPROVED** [review]
I think this should be safe, but note that I'm a bit out of date wrt the current build system with mashlib and related repos.

You should also double-check with @timbl whether he uses the bundled version that `build-dist` produced in any of his projects. (But in any case, it should be enough with the developer/unminified version of that bundle anyway, I think.)

**Comment by angelo-v** [comment]
I don't think we should remove it. Usually node_modules are not transpiled again, and I think solid-panes should be a usable on it's own and not only within mashlib, shouldn't it?

**Comment by angelo-v** [comment]
Ah ok, the module build is just done with babel directly without webpack, ok then it should be fine

**Comment by angelo-v** [comment]
Ah ok, the module build is just done with babel directly without webpack, ok then it should be fine

**Pull request closed without merging**
