### PR TITLE
[WiP] incorporate folder-table module

### PR DESCRIPTION
**Pull request by timbl**
The folder-table adds an alternative simpler folder viewer

### CODE REVIEW

**Comment by timbl** [comment]
Do not merge this until folder-table is working

**Comment by megoth** [comment]
I've taken the liberty of prefixing this with [WiP], to indicate you don't want to merge it until it's removed.

**Comment by angelo-v** [comment]
> Do not merge this until folder-table is working

Is it working in the meanwhile or what is the status?

**Comment by michielbdejong** [comment]
How is this related to https://github.com/solid/folder-pane ?

**Comment by angelo-v** [comment]
You tell me, @michielbdejong - you are the author? https://github.com/solid/folder-table/graphs/contributors

I ran into this issue when trying to integrate it https://github.com/solid/folder-table/issues/15

Therefore I am closing this PR. An up to date one can be provided if everything is supposed to work

**Comment by michielbdejong** [comment]
Fascinating, it does look like I'm the author, but I don't remember it that way.. Maybe I moved things around and that makes it look like I contributed a lot.

**Comment by angelo-v** [comment]
Weird... I cloned the repo to check the history locally and there are several of @timbl 's commits before yours. After I did that I can see those on github now as well. Those haven't been visible before :eyes:

**Pull request closed without merging**
