### PR TITLE
Need to ignore the IDE resources Jetbrains use

### PR DESCRIPTION
**Pull request by megoth**
Just a small MR to get things going

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
This should be in your own global .gitignore, no?

**Comment by megoth** [comment]
Could do that as well, but why not have it in the repo for others that use Jetbrains IDEs as well? Instead of relying on everyone having this as part of their global gitignore (I honestly didn't know of global gitignore before your comment =P )

**Comment by RubenVerborgh** [comment]
> but why not have it in the repo for others that use Jetbrains IDEs as well?

To avoid all the PRs from people using 37 other editors ;-)

**Comment by megoth** [comment]
> To avoid all the PRs from people using 37 other editors ;-)

Hah, true; we could take a copy from https://www.gitignore.io/ in that case (they usually covers all IDEs and stuff), but will maybe do that later.

Ok, just ignore this commit, I'll do this from my global gitignore.

**Pull request closed without merging**
