### PR TITLE
Rebased revamp on master

### PR DESCRIPTION
**Pull request by megoth**
Merging the revamp branch into master, introducing TypeScript, testing, CI-tooling, and a bunch of smaller changes.

@Vinnl please verify that things look good (I've run tests locally, and tested it manually in a local setup - it seems to work as intended).

### CODE REVIEW

**Comment by Vinnl** [comment]
Ah, I was working on this as well :)

With your rebased branch, I'm getting the same rdflib error I got earlier:

> ERROR in ./node_modules/file-fetch/index.js
> Module not found: Error: Can't resolve 'fs' in...

I added a commit that fixes that.

Interestingly, I'm not running into the errors I faced after that, so it looks good to me now!

**Review by Vinnl — APPROVED** [review]

**Comment by TallTed** [comment]
Argh...  Would have been good to delete the `revamp` branch, once merged!  Maybe someone with more git clue than I can figure out (and/or tell me) how to shift [my new PR](https://github.com/solid/solid-panes/pull/126) more easily than re-doing it against `master`...

**Comment by Vinnl** [comment]
@TallTed In your branch, running `git rebase master` works without conflicts, and re-applies your changes on the `master` branch. You'll then have to force push it again (`git push --force-with-lease`) - you're only supposed to do that if you're the only person working on a specific branch, which is the case here.

**Comment by TallTed** [comment]
@Vinnl - The trouble with those command-line commands is that they are not available in the github web interface, which is what I use almost exclusively. I have *ever* used the `git` commandline, but only minimally, and not at all against github repos. I figured out I could just create a [new PR against `master`](https://github.com/solid/solid-panes/pull/128), so I've done that and killed [yesterday's](https://github.com/solid/solid-panes/pull/126).

**Comment by Vinnl** [comment]
Ah, sorry @TallTed - I did not realise you only used the GitHub web interface. I've merged your changes now, thanks for the contribution.

**Pull request merged**
